version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    networks:
      dconag_network:
        ipv4_address: 172.20.0.2
    ports:
      - "1883:1883"
    volumes:
      - mqtt_data:/mosquitto/data
      - mqtt_config:/mosquitto/config
      - mqtt_log:/mosquitto/log

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    networks:
      dconag_network:
        ipv4_address: 172.20.0.3
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"   # RabbitMQ Management UI

  api:
    build: .
    container_name: dconag
    networks:
      dconag_network:
        ipv4_address: 172.20.0.4
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      dconag_network:
        ipv4_address: 172.20.0.5
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dconag_admin
      POSTGRES_PASSWORD: a5dFr2hvef

  dconag_web:
    image: httpd:2.4.59-alpine
    container_name: dconag_web
    networks:
      dconag_network:
        ipv4_address: 172.20.0.6
    ports:
      - "1000:80"
    volumes:
      - dconag_web:/usr/local/apache2/htdocs/

  dconag_admin:
    image: httpd:2.4.59-alpine
    container_name: dconag_admin
    networks:
      dconag_network:
        ipv4_address: 172.20.0.7
    ports:
      - "1001:80"
    volumes:
      - dconag_admin:/usr/local/apache2/htdocs/

  dconag_logger:
    image: node:20-slim
    container_name: dconag_logger
    networks:
      dconag_network:
        ipv4_address: 172.20.0.8
    ports:
      - "8082:80"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      dconag_network:
        ipv4_address: 172.20.0.9
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dconag.com
      PGADMIN_DEFAULT_PASSWORD: 8YnvwYW7qw
    volumes:
      - pgadmin_volume:/var/lib/pgadmin

networks:
  dconag_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  mqtt_data:
  mqtt_config:
  mqtt_log:
  postgres_volume:
  dconag_web:
  dconag_admin:
  dconag_logger:
  pgadmin_volume:
